### ISSUE TITLE
TS Dipole Model01 Simulation I=680.1A

### ISSUE THREAD

**Issue by LuanaVilela** [lnls-ima/ts-dipoles#1]
Added first model for analysis:

 ts-dipoles/model-01/simulation/magnetic/2017-08-31_TS_Dipole_Model01_Sim_X=-85_85mm_Z=-1000_1000mm_Imc=680.1A.txt

**Comment by xresende** [comment]
fieldmap analysis finished.

* integrated dipole is within spec.
* integrated quadrupole is ~7% lower than spec. transport line optics will be retuned.
* high-order multipoles are small.

model-01 APPROVED.
